#ifndef CONTROLLER_PINOUT_H
#define CONTROLLER_PINOUT_H

#define JOYSTICK1_X_PIN A0
#define JOYSTICK1_Y_PIN A1
#define JOYSTICK2_X_PIN A2
#define JOYSTICK2_Y_PIN A3
#define BUTTON_L_PIN 16
#define BUTTON_R_PIN 39
#define TFT_CS_PIN 12
#define TFT_DC_PIN 13

#endif // CONTROLLER_PINOUT_H

// #ifndef GRIPPER_PINOUT_H
// #define GRIPPER_PINOUT_H

// #define LEFT_SERVO_PIN 13
// #define RIGHT_SERVO_PIN 12
// #define SERVO_ANGLE_CONVERSION 5/3


// #endif // GRIPPER_PINOUT_H