#ifndef GRIPPER_CONTROLLER_PINOUT_H
#define GRIPPER_CONTROLLER_PINOUT_H

#define MAG_ON_PIN 12
#define MAG_OFF_PIN 13
#define MAG_MODE_PIN 14
#define GRIP_OFF_PIN 15
#define GRIP_ON_PIN 16

#endif // GRIPPER_CONTROLLER_PINOUT_H