#ifndef GRIPPER_PINOUT_H
#define GRIPPER_PINOUT_H

#define RIGHT_SERVO_PIN 12
#define LEFT_SERVO_PIN 13

#define RIGHT_MAGNET_PIN 14
#define LEFT_MAGNET_PIN 15

#define CLOSED_POS_BUTTON 5
#define OPEN_POS_BUTTON 4
#define MAGNET_POS_BUTTON 3

#define SERVO_ANGLE_CONVERSION 5/3

#define MIN_US 840
#define MAX_US 2060

#define OPEN_ANGLE 15

#endif // GRIPPER_PINOUT_H